name: ebroker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  flutter_paystack: ^1.0.7  #
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.3.0
  # flutter_local_notifications:  9.6.0 
  firebase_core_platform_interface: 5.0.0
  panorama: ^0.4.1
  http: ^0.13.3
  http_parser: any
  mime: any
  flick_video_player: ^0.5.0
  video_player: ^2.4.10
  youtube_player_flutter: ^8.1.2
  flutter_svg: 1.1.6
  shared_preferences: ^2.0.15
  flutter_native_image: 0.0.6+1
  country_code_picker: ^2.0.2
  country_picker: ^2.0.19 
  sms_autofill: ^2.2.0
  connectivity_plus: ^2.3.7
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  file_picker: ^5.2.4
  flutter_bloc: ^8.1.1
  shimmer: ^2.0.0
  cached_network_image: ^3.3.0
  intl: ^0.17.0
  rive: ^0.9.1
  octo_image: ^2.0.0
  dotted_border: ^2.0.0+3
  url_launcher: ^6.1.6 
  flutter_html: ^3.0.0-beta.1
  share_plus: ^4.4.0
  launch_review: ^3.0.1
  lottie: ^2.1.0
  #payment gatewats
  razorpay_flutter: ^1.3.5
  flutter_paypal: ^0.0.8
  flutter_sim_country_code: ^0.1.2
  mime_type: ^1.0.0
  google_maps_flutter: 2.2.6 #   google_maps_flutter: ^2.2.1
  awesome_notifications: ^0.7.4+1
  device_preview: ^1.1.0
  path_provider: ^2.0.13
  record: ^4.4.4
  audioplayers: ^3.0.1
  image_cropper: ^3.0.1
  # just_audio:
  # flutter_downloader: ^1.10.2
  # flutter_ringtone_player: ^3.2.0
  permission_handler: ^11.1.0
  open_filex: ^4.3.2
  # emoji_picker_flutter: ^1.5.2
  # rxdart: ^0.27.7
  flutter_vibrate: ^1.3.0
  firebase_dynamic_links: ^5.0.17
  package_info_plus: ^4.0.2
  fluttertoast: ^8.2.1
  hydrated_bloc: ^9.1.0
  label_marker: ^1.0.1
  flutter_typeahead: ^4.3.7
  any_link_preview: ^3.0.0
  geocoding: ^2.1.0
  flutter_stripe: ^9.4.0
  flutter_staggered_grid_view: ^0.6.2
  latlong2: ^0.9.0
  logger: ^1.4.0
  file_icon: ^1.0.0
  palette_generator: ^0.3.3+2
  carousel_slider: ^4.2.1
  firebase_analytics: ^10.1.6
  encrypt: ^5.0.3
  google_mobile_ads: ^2.4.0
  uni_links: ^0.5.1
  


dependency_overrides:
  flutter_svg : ^1.0.0
  intl: ^0.17.0
  wakelock: ^0.6.2
  package_info_plus: ^4.0.2
  wakelock_windows: any
  win32:
  flutter_launcher_icons: ^0.13.1

  # file_version_info: any


dev_dependencies:
  rename: ^2.0.1


  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - assets/image/
   - assets/svg/
   - assets/AppIcon/
   - assets/languages/
   - assets/lottie/
   - assets/riveAnimations/
   - assets/chat_background/
   - assets/chat_background/
   - assets/svg/MultiColorSvg/
   - assets/svg/Logo/
   - assets/svg/Fallback/
   - assets/city.jpg
   - assets/map.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800


      
